var _0x3f5411 = _0x35fb;

function _0x35fb(e, t) {
    var i = _0x1f7d();
    return (_0x35fb = function (e, t) {
            return i[e -= 352]
        }
    )(e, t)
}

function _0x1f7d() {
    return [
        "3AB9D23F7A4B3CSS",
        "append",
        "FreeBSD",
        "body",
        "jsToIOS",
        "WEBGL_debug_renderer_info",
        "AcroPDF.PDF",
        "vertexPosAttrib",
        "harmony",
        "MD5",
        "env",
        "4.90",
        "getWebglFp",
        "wur",
        "w19",
        "TSA9D23F7A4B3CFF",
        "shadowColor",
        "FRAGMENT_SHADER",
        "xhr",
        "rgba(0, 0, 200, 0.5)",
        "parseUa",
        "enableVertexAttribArray",
        "getFpServerDomain",
        "self",
        "powerPC",
        "26112069mFthDf",
        "stroke",
        "toDataURL",
        "getSdkToken",
        "stringify",
        "__selenium_evaluate",
        "ucbrowser",
        "Msxml3.XMLHTTP",
        "_version",
        "color",
        "application/x-www-form-urlencoded;charset=UTF-8",
        "sendRequest error : ",
        "jdhapp",
        "jdd01",
        "alphabetic",
        "innerHeight",
        "attachShader",
        "report log error :",
        "get",
        "DeviceFingerprintBridge",
        "script",
        "font",
        "TDCCtl.TDCCtl",
        "freshApp",
        "getJsToken",
        "PR flacks quiz gym: TV DJ box when? ☠",
        "freebsd",
        "2712095FEPJlV",
        "getCurrentPageProtocol",
        "getPositionInfo",
        "MAX_VARYING_VECTORS",
        "SymbianOS",
        "sendRequest",
        "getSupportedExtensions",
        "href",
        "getHardwareConcurrency",
        "2.0.0",
        "ceil",
        "windows",
        "isIos",
        "powerpc",
        "getNavigatorPlatform",
        "the world",
        "FFA9D23F7A4B3CSS",
        "sdkToken",
        "MOZ_EXT_texture_filter_anisotropic",
        "getBrowserMode",
        "_is_jdsh_wkwebview",
        "yjcapp",
        "isIOS",
        "DEPTH_TEST",
        "jra.jd.com",
        "nativeMap",
        "JDDoctor App Bridge CALL ERROR",
        "callTime",
        "jdapp",
        "IvepNative",
        "contextName",
        "getExtension",
        "yes",
        "charCodeAt",
        "responseTime",
        "14vPZEal",
        "apply",
        "serif",
        "timeout",
        "sun",
        "safari",
        "SWCtl.SWCtl",
        "isValidJsToken",
        "_AppBridgeCallback",
        "RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)",
        "yhdapp",
        "sessionStorage",
        "Adodb.Stream",
        "Worker",
        "MAX_CUBE_MAP_TEXTURE_SIZE",
        "sdkTokenKey",
        "getAttribLocation",
        "callBridge",
        "canvas_fp_md5",
        "fonts",
        "fontSize",
        "type",
        "getLocalStorageSupport",
        "iphone",
        "withCredentials",
        "https://mllog.jd.com/mlog/unite.do",
        "RED_BITS",
        "getComputedStyle",
        "compareVersion",
        "strokeStyle",
        "sessionStorageKey",
        "white",
        "cookieEnabled",
        "strict",
        "https://",
        "trim",
        "ipad",
        "isSdkTokenFinished",
        "7.0.2",
        "shadingLV",
        "external",
        "devicePixelRatio,screenTop,screenLeft",
        "DJ App Bridge CALL ERROR",
        "isJsTokenFinished",
        "getItem",
        "TDEncrypt",
        "jdjr",
        "SymbianOS/",
        "globalStorage",
        "reportCnt",
        "indexOf",
        "documentMode",
        "each",
        "jsTokenKey",
        "WebKitBlobBuilder",
        "suffixes",
        "set",
        "object",
        "YHD App Bridge CALL ERROR",
        "getTimezoneOffset",
        "BLUE_BITS",
        "navigator",
        "getLanguage",
        "timezoneOffset",
        "unix",
        "https:",
        "getCanvasFp",
        "hardwareConcurrency",
        "__fxdriver_unwrapped",
        "getFeature",
        "expires=",
        "text/javascript",
        "browserVersion",
        "giaDKey",
        "createObjectURL",
        "TRIANGLE_STRIP",
        "undefined",
        "getPlugins",
        "send",
        "getAddBehaviorSupport",
        "osf1",
        "compileShader",
        "jdjr-app",
        "getWebglCanvas",
        "shadowOffsetX",
        "JS-M",
        "resp parse error",
        "biometricForJS",
        "getCallbackName",
        "NetBSD",
        "JD APP VERSION NOT SUPPORT",
        "appBridgeMap",
        "openDatabase",
        "4.6.0",
        "Opera",
        "firefox",
        "parse",
        "cookie",
        "navigator/",
        "env collect error",
        "addBehavior",
        "depthFunc",
        "floor",
        "enable",
        "match",
        "02_mt_5LXK_60653970589",
        "MAX_VERTEX_UNIFORM_VECTORS",
        "SHADING_LANGUAGE_VERSION",
        "width",
        "setItem",
        "reportWorker",
        "] Cost time :",
        "iapDeviceCallback",
        "createShader",
        "IRIX",
        "initFunc",
        "TSA9D23F7A4B3CSS",
        "webgl,experimental-webgl,moz-webgl,webkit-3d",
        "yhd",
        "deviceTime",
        "w13",
        "getUserAgent",
        "appversion/",
        "getOpenDatabaseSupport",
        "6.0",
        "YJC App Bridge CALL ERROR",
        "language",
        "_selenium",
        "push",
        "UNMASKED_RENDERER_WEBGL",
        "callPhantom",
        "Msxml2.DOMDocument",
        "callSelenium",
        "__webdriver_script_func",
        "sdkBizId",
        "onBiometricFinish",
        "__selenium_unwrapped",
        "AcroPDF.PDF,Adodb.Stream,AgControl.AgControl,DevalVRXCtrl.DevalVRXCtrl.1,MacromediaFlashPaper.MacromediaFlashPaper,Msxml2.DOMDocument,Msxml2.XMLHTTP,PDF.PdfCtrl,QuickTime.QuickTime,QuickTimeCheckObject.QuickTimeCheck.1,RealPlayer,RealPlayer.RealPlayer(tm) ActiveX Control (32-bit),RealVideo.RealVideo(tm) ActiveX Control (32-bit),rmocx.RealPlayer G2 Control,Scripting.Dictionary,Shell.UIHelper,ShockwaveFlash.ShockwaveFlash,SWCtl.SWCtl,TDCCtl.TDCCtl,WMPlayer.OCX",
        "~~~",
        "hash128",
        "tencenttraveler",
        "fp keys:",
        "getCurrentRootDomain",
        "JS BRIDGE CALL ERROR",
        "join",
        "JDAppUnite",
        "gia_d",
        "COLOR_BUFFER_BIT",
        "substring",
        "safari/",
        "shaderSource",
        "map",
        "useProgram",
        "endsWith",
        ".localdomain",
        "RENDERER",
        "taintEnabled",
        "STATIC_DRAW",
        "QQ???",
        "message",
        "getSupportFonts",
        "FLOAT",
        "fp collect error",
        "getCookie",
        "open",
        "MAX_VERTEX_ATTRIBS",
        "wuv:",
        "OSF1",
        "statusText",
        "w21",
        "innerHTML",
        "djJava",
        "ActiveBorder,ActiveCaption,AppWorkspace,Background,ButtonFace,ButtonHighlight,ButtonShadow,ButtonText,CaptionText,GrayText,Highlight,HighlightText,InactiveBorder,InactiveCaption,InactiveCaptionText,InfoBackground,InfoText,Menu,MenuText,Scrollbar,ThreeDDarkShadow,ThreeDFace,ThreeDHighlight,ThreeDLightShadow,ThreeDShadow,Window,WindowFrame,WindowText",
        "nativeForEach",
        "924232QdonJN",
        "XMLHttpRequest",
        "bizTimeout",
        "indexedDb",
        "test",
        "UC???",
        "height",
        "01234567",
        "fpKey",
        "indexedDB",
        "jsToken",
        "QuickTimeCheckObject.QuickTimeCheck.1",
        "60px 'Not a real font'",
        "token",
        "UNSUPPORTED APP",
        "forEach",
        "JD JS SDK Callback ERROR",
        "responseText",
        "deMap",
        "notifyMessageToNative",
        "netbsd",
        "feature",
        "onreadystatechange",
        "BlobBuilder",
        "worker",
        "callNative",
        "round",
        "getFpExcludeOptions",
        "nt 6.0",
        "ALIASED_POINT_SIZE_RANGE",
        "JDTRiskBridgeUtil",
        "stack",
        "createElement",
        "offsetWidth",
        "linkProgram",
        "w17",
        "uniformOffset",
        "stk",
        "msie ",
        "getStoreCheck",
        "FROM LOCAL CACHE",
        "jdd03",
        "isSupportApp",
        "Content-Type",
        "load",
        "offsetHeight",
        "getBrowserInfo",
        "FINISHED",
        "plugins",
        "respText",
        "timeout_",
        "mac",
        "wuv",
        "offsetUniform",
        "style",
        "uniform2f",
        "clientVersion",
        "appName",
        "72px",
        "lil",
        "callAppBridge",
        "bsd",
        "4game;AdblockPlugin;AdobeExManCCDetect;AdobeExManDetect;Alawar NPAPI utils;Aliedit Plug-In;Alipay Security Control 3;AliSSOLogin plugin;AmazonMP3DownloaderPlugin;AOL Media Playback Plugin;AppUp;ArchiCAD;AVG SiteSafety plugin;Babylon ToolBar;Battlelog Game Launcher;BitCometAgent;Bitdefender QuickScan;BlueStacks Install Detector;CatalinaGroup Update;Citrix ICA Client;Citrix online plug-in;Citrix Receiver Plug-in;Coowon Update;DealPlyLive Update;Default Browser Helper;DivX Browser Plug-In;DivX Plus Web Player;DivX VOD Helper Plug-in;doubleTwist Web Plugin;Downloaders plugin;downloadUpdater;eMusicPlugin DLM6;ESN Launch Mozilla Plugin;ESN Sonar API;Exif Everywhere;Facebook Plugin;File Downloader Plug-in;FileLab plugin;FlyOrDie Games Plugin;Folx 3 Browser Plugin;FUZEShare;GDL Object Web Plug-in 16.00;GFACE Plugin;Ginger;Gnome Shell Integration;Google Earth Plugin;Google Earth Plug-in;Google Gears 0.5.33.0;Google Talk Effects Plugin;Google Update;Harmony Firefox Plugin;Harmony Plug-In;Heroes & Generals live;HPDetect;Html5 location provider;IE Tab plugin;iGetterScriptablePlugin;iMesh plugin;Kaspersky Password Manager;LastPass;LogMeIn Plugin 1.0.0.935;LogMeIn Plugin 1.0.0.961;Ma-Config.com plugin;Microsoft Office 2013;MinibarPlugin;Native Client;Nitro PDF Plug-In;Nokia Suite Enabler Plugin;Norton Identity Safe;npAPI Plugin;NPLastPass;NPPlayerShell;npTongbuAddin;NyxLauncher;Octoshape Streaming Services;Online Storage plug-in;Orbit Downloader;Pando Web Plugin;Parom.TV player plugin;PDF integrado do WebKit;PDF-XChange Viewer;PhotoCenterPlugin1.1.2.2;Picasa;PlayOn Plug-in;QQ2013 Firefox Plugin;QQDownload Plugin;QQMiniDL Plugin;QQMusic;RealDownloader Plugin;Roblox Launcher Plugin;RockMelt Update;Safer Update;SafeSearch;Scripting.Dictionary;SefClient Plugin;Shell.UIHelper;Silverlight Plug-In;Simple Pass;Skype Web Plugin;SumatraPDF Browser Plugin;Symantec PKI Client;Tencent FTN plug-in;Thunder DapCtrl NPAPI Plugin;TorchHelper;Unity Player;Uplay PC;VDownloader;Veetle TV Core;VLC Multimedia Plugin;Web Components;WebKit-integrierte PDF;WEBZEN Browser Extension;Wolfram Mathematica;WordCaptureX;WPI Detector 1.4;Yandex Media Plugin;Yandex PDF Viewer;YouTube Plug-in;zako",
        "UNMASKED_VENDOR_WEBGL",
        "success",
        "3.1.2",
        "userAgent",
        "function",
        "isValidSdkToken",
        "LEQUAL",
        "JR BRIDGE CALL ERROR",
        "cleanAndPushDeS",
        "clientVersion=([^&]*)(&|$)",
        "postMessage",
        "compatMode",
        "getEnvExcludeOptions",
        "Microsoft.XMLHTTP",
        "antialias",
        "VENDOR",
        "7freshapp",
        "clearColor",
        "5.0.1",
        "startTime",
        "lineCap",
        "extensions:",
        "http://",
        "HASH",
        "toString",
        "w16",
        "MozBlobBuilder",
        "doNotTrack",
        "MobileNavi",
        "_Selenium_IDE_Recorder",
        "wur:",
        "10yRIYMu",
        "MAX_VERTEX_TEXTURE_IMAGE_UNITS",
        "duraTime",
        "setTime",
        "cpuClass",
        "hidden",
        "JDH App Bridge CALL ERROR",
        "attrVertex",
        "toUTCString",
        "collect env data :",
        "ontimeout",
        "6.5.0",
        "indexedDbKey",
        "innerWidth",
        "getContext",
        "_*_UYBN6YGTNO6DHPVB",
        "app",
        "5FkNzFH",
        "experimental-webgl",
        "JR JS Bridge Result :",
        "deviceInfo",
        "error",
        "WEBKIT_EXT_texture_filter_anisotropic",
        "VERSION",
        "jdltapp",
        "localStorage",
        "javaEnabled",
        "JR BRIDGE NOT SUPPORT",
        "rmocx.RealPlayer G2 Control.1",
        "createWorker",
        "WebGLRenderingContext",
        "createBuffer",
        "sogoumobilebrowser",
        "EXT_texture_filter_anisotropic",
        "platform",
        "version",
        "webgl",
        "fast",
        "MAX_VIEWPORT_DIMS",
        "call",
        "RealVideo.RealVideo(tm) ActiveX Control (32-bit)",
        "mmmmmmmmmmlli",
        "Skype.Detection",
        "#42e1a2",
        "BATQW722QTLYVCRD",
        "9539760GLukeg",
        "__fp_domain",
        "randomStr",
        "JXTJ App Bridge CALL ERROR",
        "div",
        "colorDepth",
        "code",
        "getParameter",
        "jsDefault",
        "nt 6.1",
        "protocol",
        "vertexAttribPointer",
        "subVers",
        "red",
        "setRequestHeader",
        "location",
        "XWebView",
        "ActiveXObject",
        "fontFamily",
        "data",
        "MAX_TEXTURE_IMAGE_UNITS",
        "__webdriver_unwrapped",
        "getOsInfo",
        "execute",
        "fillRect",
        "MacromediaFlashPaper.MacromediaFlashPaper",
        "availHeight,availWidth,colorDepth,bufferDepth,deviceXDPI,deviceYDPI,height,width,logicalXDPI,logicalYDPI,pixelDepth,updateInterval",
        "getTime",
        "webglversion",
        "getPropertyValue",
        "interval",
        "getBlob",
        "GIA_LDE_MAP_KEY",
        "getDoNotTrack",
        "onerror",
        "getSessionStorageSupport",
        "getSupportApp",
        "isRpTok",
        "23IL<N01c7KvwZO56RSTAfghiFyzWJqVabGH4PQdopUrsCuX*xeBjkltDEmn89.-",
        "FROM REGX",
        "registerAppBridge",
        "6186664UtTfbI",
        "msie",
        "store",
        "CA1AN5BV0CA8DS2E3F",
        "canvasFpKey",
        "getJdEid",
        "getBizId",
        "browserMode",
        "fpTsKey",
        "top",
        "getUrlQueryStr",
        "addBehaviorKey",
        "sun os",
        "opera",
        "irix",
        "numItems",
        "src",
        "2165043hiuUKV",
        "nt 5.1",
        "linux",
        "async",
        "getScreenInfo",
        "WMPlayer.OCX",
        "w15",
        "messageHandlers",
        "jddoctor",
        "__global_jdt_risk_fp_exec",
        "global_",
        "getCurrentPageUrl",
        "removeChild",
        "???????",
        "hasOwnProperty",
        "toLowerCase",
        "ShockwaveFlash.ShockwaveFlash",
        "JR SDK call ERROR",
        "#1a3bc1",
        "00000000",
        "FP function : [",
        "split",
        "supportVersion",
        "bufferData",
        "drawArrays",
        "localStorageKey",
        "fillStyle",
        "SUCCESS",
        "screenResolution",
        "eid",
        "bizId",
        "string",
        "JR CALLBACK ERROR",
        "_gia_d",
        "ibm os/2",
        "jdd",
        "MAX_TEXTURE_MAX_ANISOTROPY_EXT",
        "win",
        "applewebkit_chrome",
        "canvas",
        "isSupportBioBridge",
        "callMethod",
        "itemSize",
        "onmessage = function (event) {\n    var data = JSON.parse(event.data);\n    try {\n        var httpRequest;\n        try {\n            httpRequest = new XMLHttpRequest();\n        } catch (h) {}\n        if (!httpRequest)\n            try {\n                httpRequest = new (window['ActiveXObject'])('Microsoft.XMLHTTP')\n            } catch (l) {}\n        if (!httpRequest)\n            try {\n                httpRequest = new (window['ActiveXObject'])('Msxml2.XMLHTTP')\n            } catch (r) {}\n        if (!httpRequest)\n            try {\n                httpRequest = new (window['ActiveXObject'])('Msxml3.XMLHTTP')\n            } catch (n) {}\n\n        if(data){\n            httpRequest['open']('POST', data.url, data.async);\n            httpRequest['withCredentials'] = true;\n            httpRequest['setRequestHeader']('Content-Type', data.isJson ? 'application/json;charset=UTF-8' : 'application/x-www-form-urlencoded;charset=UTF-8');\n            httpRequest['onreadystatechange'] = function () {\n                if (4 === httpRequest['readyState'] && 200 === httpRequest['status']) {\n                    postMessage(httpRequest.responseText);\n                }\n            };\n            httpRequest['send'](data.data);\n        }\n\n    }catch (e){console.error(e);}\n};",
        "jmapp",
        "?????",
        "status",
        "isReady",
        "errTrace",
        "getIEPluginsString",
        "__webdriver_evaluate",
        "webkit",
        "getScreenResolution",
        "etn",
        "getCanvasInfo",
        "UNSUPPORTED APP.",
        "w10",
        "MAX_FRAGMENT_UNIFORM_VECTORS",
        "MAX_RENDERBUFFER_SIZE",
        "BiometricApi",
        "/jsTk.do",
        "appendChild",
        "storeCheck",
        "Scripting.Dictionary",
        "__driver_evaluate",
        "length",
        "183422cJwBpE",
        "bp_bizid",
        "position",
        "callBiological",
        "getEncryptedCollectInfo",
        "eidKey",
        "GetVersions",
        "charAt",
        "ibm",
        "onabort",
        "osVersion",
        "name",
        "isDegrade",
        "doCallBridge",
        "extensions",
        "getColorRgb",
        "prototype",
        "DevalVRXCtrl.DevalVRXCtrl.1",
        " Bridge Method not implemented",
        "MAX_COMBINED_TEXTURE_IMAGE_UNITS",
        "bridgeBiologicalProbe",
        "nt 5.0",
        "obtainPin",
        "aix",
        "_bioDeviceSdkTokenCb",
        "ldeKey",
        "span",
        "QuickTime.QuickTime",
        "slice",
        "tdHash",
        "fillText",
        "visibility",
        "screen",
        "__driver_unwrapped",
        "4.2.8.0",
        "//gias.jd.com/dy/js/mom.js?bizId=",
        "jdbmall",
        "ARRAY_BUFFER",
        "log",
        "abort_",
        "applewebkit/",
        "startsWith",
        "4.1.8",
        "getRegularPluginsString",
        "&d=",
        "Microsoft Internet Explorer",
        "ALIASED_LINE_WIDTH_RANGE",
        "metasr",
        "createProgram",
        "w24",
        "chrome/",
        "reportTime",
        "Msxml2.XMLHTTP"
    ];
}


var jdtRiskEncryptUtil = (e => {
    var u, p = _0x3f5411;

    function s(e, t, i, n, r, o) {
        return w((t = w(w(t, e), w(n, o))) << r | t >>> 32 - r, i)
    }

    function g(e, t, i, n, r, o, a) {
        return s(t & i | ~t & n, e, t, r, o, a)
    }

    function f(e, t, i, n, r, o, a) {
        return s(t & n | i & ~n, e, t, r, o, a)
    }

    function h(e, t, i, n, r, o, a) {
        return s(t ^ i ^ n, e, t, r, o, a)
    }

    function v(e, t, i, n, r, o, a) {
        return s(i ^ (t | ~n), e, t, r, o, a)
    }

    function w(e, t) {
        var i = (65535 & e) + (65535 & t);
        return (e >> 16) + (t >> 16) + (i >> 16) << 16 | 65535 & i
    }

    function _(e, t) {
        e = [e[0] >>> 16, 65535 & e[0], e[1] >>> 16, 65535 & e[1]],
            t = [t[0] >>> 16, 65535 & t[0], t[1] >>> 16, 65535 & t[1]];
        var i = [0, 0, 0, 0];
        return i[3] += e[3] + t[3],
            i[2] += i[3] >>> 16,
            i[3] &= 65535,
            i[2] += e[2] + t[2],
            i[1] += i[2] >>> 16,
            i[2] &= 65535,
            i[1] += e[1] + t[1],
            i[0] += i[1] >>> 16,
            i[1] &= 65535,
            i[0] += e[0] + t[0],
            i[0] &= 65535,
            [i[0] << 16 | i[1], i[2] << 16 | i[3]]
    }

    function k(e, t) {
        e = [e[0] >>> 16, 65535 & e[0], e[1] >>> 16, 65535 & e[1]],
            t = [t[0] >>> 16, 65535 & t[0], t[1] >>> 16, 65535 & t[1]];
        var i = [0, 0, 0, 0];
        return i[3] += e[3] * t[3],
            i[2] += i[3] >>> 16,
            i[3] &= 65535,
            i[2] += e[2] * t[3],
            i[1] += i[2] >>> 16,
            i[2] &= 65535,
            i[2] += e[3] * t[2],
            i[1] += i[2] >>> 16,
            i[2] &= 65535,
            i[1] += e[1] * t[3],
            i[0] += i[1] >>> 16,
            i[1] &= 65535,
            i[1] += e[2] * t[2],
            i[0] += i[1] >>> 16,
            i[1] &= 65535,
            i[1] += e[3] * t[1],
            i[0] += i[1] >>> 16,
            i[1] &= 65535,
            i[0] += e[0] * t[3] + e[1] * t[2] + e[2] * t[1] + e[3] * t[0],
            i[0] &= 65535,
            [i[0] << 16 | i[1], i[2] << 16 | i[3]]
    }

    function S(e, t) {
        return 32 == (t %= 64) ? [e[1], e[0]] : t < 32 ? [e[0] << t | e[1] >>> 32 - t, e[1] << t | e[0] >>> 32 - t] : [e[1] << (t -= 32) | e[0] >>> 32 - t, e[0] << t | e[1] >>> 32 - t]
    }

    function R(e, t) {
        return 0 == (t %= 64) ? e : t < 32 ? [e[0] << t | e[1] >>> 32 - t, e[1] << t] : [e[1] << t - 32, 0]
    }

    function C(e, t) {
        return [e[0] ^ t[0], e[1] ^ t[1]]
    }

    function m(e) {
        return e = C(e, [0, e[0] >>> 1]),
            e = C(e = k(e, [4283543511, 3981806797]), [0, e[0] >>> 1]),
            C(e = k(e, [3301882366, 444984403]), [0, e[0] >>> 1])
    }

    return e[p(361)] = {
        hex_md5: function (e) {
            var t = p;
            if (null == e || "" == e)
                return "";
            for (var i = ((e, t) => {
                    var i = _0x35fb;
                    e[t >> 5] |= 128 << t % 32,
                        e[14 + (64 + t >>> 9 << 4)] = t;
                    for (var n = 1732584193, r = -271733879, o = -1732584194, a = 271733878, s = 0; s < e[i(875)]; s += 16) {
                        var c = n
                            , l = r
                            , d = o
                            , u = a
                            , n = g(n, r, o, a, e[s + 0], 7, -680876936)
                            , a = g(a, n, r, o, e[s + 1], 12, -389564586)
                            , o = g(o, a, n, r, e[s + 2], 17, 606105819)
                            , r = g(r, o, a, n, e[s + 3], 22, -1044525330);
                        n = g(n, r, o, a, e[s + 4], 7, -176418897),
                            a = g(a, n, r, o, e[s + 5], 12, 1200080426),
                            o = g(o, a, n, r, e[s + 6], 17, -1473231341),
                            r = g(r, o, a, n, e[s + 7], 22, -45705983),
                            n = g(n, r, o, a, e[s + 8], 7, 1770035416),
                            a = g(a, n, r, o, e[s + 9], 12, -1958414417),
                            o = g(o, a, n, r, e[s + 10], 17, -42063),
                            r = g(r, o, a, n, e[s + 11], 22, -1990404162),
                            n = g(n, r, o, a, e[s + 12], 7, 1804603682),
                            a = g(a, n, r, o, e[s + 13], 12, -40341101),
                            o = g(o, a, n, r, e[s + 14], 17, -1502002290),
                            n = f(n, r = g(r, o, a, n, e[s + 15], 22, 1236535329), o, a, e[s + 1], 5, -165796510),
                            a = f(a, n, r, o, e[s + 6], 9, -1069501632),
                            o = f(o, a, n, r, e[s + 11], 14, 643717713),
                            r = f(r, o, a, n, e[s + 0], 20, -373897302),
                            n = f(n, r, o, a, e[s + 5], 5, -701558691),
                            a = f(a, n, r, o, e[s + 10], 9, 38016083),
                            o = f(o, a, n, r, e[s + 15], 14, -660478335),
                            r = f(r, o, a, n, e[s + 4], 20, -405537848),
                            n = f(n, r, o, a, e[s + 9], 5, 568446438),
                            a = f(a, n, r, o, e[s + 14], 9, -1019803690),
                            o = f(o, a, n, r, e[s + 3], 14, -187363961),
                            r = f(r, o, a, n, e[s + 8], 20, 1163531501),
                            n = f(n, r, o, a, e[s + 13], 5, -1444681467),
                            a = f(a, n, r, o, e[s + 2], 9, -51403784),
                            o = f(o, a, n, r, e[s + 7], 14, 1735328473),
                            n = h(n, r = f(r, o, a, n, e[s + 12], 20, -1926607734), o, a, e[s + 5], 4, -378558),
                            a = h(a, n, r, o, e[s + 8], 11, -2022574463),
                            o = h(o, a, n, r, e[s + 11], 16, 1839030562),
                            r = h(r, o, a, n, e[s + 14], 23, -35309556),
                            n = h(n, r, o, a, e[s + 1], 4, -1530992060),
                            a = h(a, n, r, o, e[s + 4], 11, 1272893353),
                            o = h(o, a, n, r, e[s + 7], 16, -155497632),
                            r = h(r, o, a, n, e[s + 10], 23, -1094730640),
                            n = h(n, r, o, a, e[s + 13], 4, 681279174),
                            a = h(a, n, r, o, e[s + 0], 11, -358537222),
                            o = h(o, a, n, r, e[s + 3], 16, -722521979),
                            r = h(r, o, a, n, e[s + 6], 23, 76029189),
                            n = h(n, r, o, a, e[s + 9], 4, -640364487),
                            a = h(a, n, r, o, e[s + 12], 11, -421815835),
                            o = h(o, a, n, r, e[s + 15], 16, 530742520),
                            n = v(n, r = h(r, o, a, n, e[s + 2], 23, -995338651), o, a, e[s + 0], 6, -198630844),
                            a = v(a, n, r, o, e[s + 7], 10, 1126891415),
                            o = v(o, a, n, r, e[s + 14], 15, -1416354905),
                            r = v(r, o, a, n, e[s + 5], 21, -57434055),
                            n = v(n, r, o, a, e[s + 12], 6, 1700485571),
                            a = v(a, n, r, o, e[s + 3], 10, -1894986606),
                            o = v(o, a, n, r, e[s + 10], 15, -1051523),
                            r = v(r, o, a, n, e[s + 1], 21, -2054922799),
                            n = v(n, r, o, a, e[s + 8], 6, 1873313359),
                            a = v(a, n, r, o, e[s + 15], 10, -30611744),
                            o = v(o, a, n, r, e[s + 6], 15, -1560198380),
                            r = v(r, o, a, n, e[s + 13], 21, 1309151649),
                            n = v(n, r, o, a, e[s + 4], 6, -145523070),
                            a = v(a, n, r, o, e[s + 11], 10, -1120210379),
                            o = v(o, a, n, r, e[s + 2], 15, 718787259),
                            r = v(r, o, a, n, e[s + 9], 21, -343485551),
                            n = w(n, c),
                            r = w(r, l),
                            o = w(o, d),
                            a = w(a, u)
                    }
                    return Array(n, r, o, a)
                }
            )((e => {
                    var t = _0x35fb;
                    if (null == e || "" == e)
                        return "";
                    for (var i = Array(), n = 0; n < 8 * e[t(875)]; n += 8)
                        i[n >> 5] |= (255 & e[t(437)](n / 8)) << n % 32;
                    return i
                }
            )(e), 8 * e[t(875)]), n = "0123456789abcdef", r = "", o = 0; o < 4 * i[t(875)]; o++)
                r += n[t(883)](i[o >> 2] >> o % 4 * 8 + 4 & 15) + n[t(883)](i[o >> 2] >> o % 4 * 8 & 15);
            return r
        }
    },
        e[p(699)] = {
            hash128: function (e, t) {
                for (var i = p, n = e, e = t, t = (n = n || "")[i(875)] % 16, r = n[i(875)] - t, o = [0, e = e || 0], a = [0, e], s = [0, 0], c = [0, 0], l = [2277735313, 289559509], d = [1291169091, 658871167], u = 0; u < r; u += 16)
                    s = [255 & n[i(437)](u + 4) | (255 & n.charCodeAt(u + 5)) << 8 | (255 & n[i(437)](u + 6)) << 16 | (255 & n[i(437)](u + 7)) << 24, 255 & n[i(437)](u) | (255 & n[i(437)](u + 1)) << 8 | (255 & n[i(437)](u + 2)) << 16 | (255 & n.charCodeAt(u + 3)) << 24],
                        c = [255 & n[i(437)](u + 12) | (255 & n[i(437)](u + 13)) << 8 | (255 & n[i(437)](u + 14)) << 16 | (255 & n[i(437)](u + 15)) << 24, 255 & n[i(437)](u + 8) | (255 & n.charCodeAt(u + 9)) << 8 | (255 & n[i(437)](u + 10)) << 16 | (255 & n[i(437)](u + 11)) << 24],
                        s = S(s = k(s, l), 31),
                        o = _(o = S(o = C(o, s = k(s, d)), 27), a),
                        o = _(k(o, [0, 5]), [0, 1390208809]),
                        c = S(c = k(c, d), 33),
                        a = _(a = S(a = C(a, c = k(c, l)), 31), o),
                        a = _(k(a, [0, 5]), [0, 944331445]);
                switch (s = [0, 0],
                    c = [0, 0],
                    t) {
                    case 15:
                        c = C(c, R([0, n.charCodeAt(u + 14)], 48));
                    case 14:
                        c = C(c, R([0, n[i(437)](u + 13)], 40));
                    case 13:
                        c = C(c, R([0, n[i(437)](u + 12)], 32));
                    case 12:
                        c = C(c, R([0, n[i(437)](u + 11)], 24));
                    case 11:
                        c = C(c, R([0, n[i(437)](u + 10)], 16));
                    case 10:
                        c = C(c, R([0, n.charCodeAt(u + 9)], 8));
                    case 9:
                        c = k(c = C(c, [0, n[i(437)](u + 8)]), d),
                            a = C(a, c = k(c = S(c, 33), l));
                    case 8:
                        s = C(s, R([0, n[i(437)](u + 7)], 56));
                    case 7:
                        s = C(s, R([0, n[i(437)](u + 6)], 48));
                    case 6:
                        s = C(s, R([0, n.charCodeAt(u + 5)], 40));
                    case 5:
                        s = C(s, R([0, n[i(437)](u + 4)], 32));
                    case 4:
                        s = C(s, R([0, n[i(437)](u + 3)], 24));
                    case 3:
                        s = C(s, R([0, n[i(437)](u + 2)], 16));
                    case 2:
                        s = C(s, R([0, n[i(437)](u + 1)], 8));
                    case 1:
                        s = k(s = C(s, [0, n.charCodeAt(u)]), l),
                            o = C(o, s = k(s = S(s, 31), d))
                }
                return o = _(o = C(o, [0, n.length]), a = C(a, [0, n.length])),
                    a = _(a, o),
                    o = _(o = m(o), a = m(a)),
                    a = _(a, o),
                ("00000000" + (o[0] >>> 0)[i(700)](16)).slice(-8) + (i(829) + (o[1] >>> 0).toString(16))[i(904)](-8) + (i(829) + (a[0] >>> 0)[i(700)](16)).slice(-8) + (i(829) + (a[1] >>> 0)[i(700)](16))[i(904)](-8)
            }
        },
        e[p(484)] = (u = p(790),
                function (e) {
                    for (var t, i, n, r, o, a = p, s = JSON[a(381)](e), s = encodeURIComponent(s), c = "", l = "", d = 0; n = (t = s[a(437)](d++)) >> 2,
                        r = (3 & t) << 4 | (t = s[a(437)](d++)) >> 4,
                        o = (15 & t) << 2 | (i = s.charCodeAt(d++)) >> 6,
                        l = 63 & i,
                        isNaN(t) ? o = l = 64 : isNaN(i) && (l = 64),
                        c = c + u[a(883)](n) + u.charAt(r) + u[a(883)](o) + u[a(883)](l),
                        o = l = "",
                    d < s[a(875)];)
                        ;
                    return c + "/"
                }
        ),
        e
})(jdtRiskEncryptUtil || {});


function generate_webglFp(r) {
    return jdtRiskEncryptUtil['HASH']['hash128'](r.join('~~~'), 31);
}